"""Constants for Gemini service configuration."""

DEFAULT_TEMPERATURE = 1.0
DEFAULT_TOP_P = 1.0
DEFAULT_CACHE_MIN_TOKENS = 32768
DEFAULT_CACHE_TTL_MINUTES = 60
DEFAULT_MAX_HISTORY = 50
CACHE_REFRESH_BUFFER_MIN_MINUTES = 1
CACHE_REFRESH_BUFFER_MAX_MINUTES = 5

# Display Constants
REQUEST_PREVIEW_LENGTH = 200
RESPONSE_TEXT_PREVIEW_LENGTH = 200
HISTORY_DISPLAY_LIMIT = 5
